<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FunctionEvolution</RootNamespace>
    <AssemblyName>FunctionEvolution</AssemblyName>
    <Company>ubb</Company>
    <Copyright>Copyright © ubb 2006</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZedGraph" Version="5.1.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
